### ISSUE TITLE
启用saekv作为sessions储存报错

### ISSUE THREAD

**Issue by zlowly** [chariothy/laravel4-sae#3]
页面错误信息里
 InvalidArgumentException
…/­vendor/­symfony/­finder/­Symfony/­Component/­Finder/­Finder.php 667
The "saekv:///data1/www/htdocs/363/zsy13802731024/1/app/storage/sessions" directory does not exist.
似乎sessions的路径中saekv后面三个斜杠有问题，应该是wrapper和绝对路径合并产生的，我修改了start.php，用ltrim截取掉path.storage开头的斜杠才合并就没问题了。
$app->instance("path.storage", $config['sae']['wrapper'].ltrim($app['path.storage'],"/"));
当然直接改wrapper为saekv:/也能解决，不过好像有点别扭。

**Comment by chariothy** [comment]
不是三个斜杠有问题，是因为你的项目原来是在本地调试的，sessions是生产在本地的storage目录下。上传到SAE去之后，它还到这个目录下读sessions，肯定是不存在了。这种情况只要刷新一下页面，让它在新的位置再生成一次session就可以了。本地调试后再上传时，这种情况是一定会存在的。

**Comment by chariothy** [comment]
Not a question.
