### ISSUE TITLE
composer 被强 手动安装

### ISSUE THREAD

**Issue by wutong** [chariothy/laravel4-sae#4]
关于手动修改 laravel4 使之可以在 sae上运行，
该添加哪些文件，添加或修改哪些代码？
能告诉下 步骤么～～

**Comment by chariothy** [comment]
你的意思是不想用laravel4-sae，而是手动修改？
这个说起来就太麻烦了。你直接看源码不就知道修改了哪些地方了。

**Comment by wutong** [comment]
@chariothy 源码 看不大懂 T.T
能抽个时间录个视频么？ 哈哈 :smiley:

**Comment by wutong** [comment]
@chariothy 只要基本的 app/storage 的迁移就够啦 :pray:

**Comment by wutong** [comment]
@chariothy 弱弱的问下 如果手动修改的话，是不是只改
