### ISSUE TITLE
如何在sae上建立数据库迁移？

### ISSUE THREAD

**Issue by bitzhuxb** [chariothy/laravel4-sae#6]
php artisan migrate  类似这种语句 在localhost是可以在本地库建表的。但是sae中如何建表？

**Comment by chariothy** [comment]
这个我没试过，但是在config中设置过之后，应该就对Laravel透明了。也就是说一样用，底层都是pdo。

发送自 Outlook




On Sat, Mar 14, 2015 at 9:14 PM -0700, "Zhu Xiangbin" <notifications@github.com> wrote:












php artisan migrate  类似这种语句 在localhost是可以在本地库建表的。但是sae中如何建表？

**Comment by bitzhuxb** [comment]
手动触发脚本建表是可以的，php artisan migrate 命令是不可以用的。

**Comment by chariothy** [comment]
等我有空时看看源码看。

发送自 Outlook




On Wed, Mar 18, 2015 at 5:10 AM -0700, "Zhu Xiangbin" <notifications@github.com> wrote:












手动触发脚本建表是可以的，php artisan migrate 命令是不可以用的。
