### ISSUE TITLE
可否用在 4.2 上？

### ISSUE THREAD

**Issue by viko16** [chariothy/laravel4-sae#8]
[SAE 已经开始测试](http://saebbs.com/forum.php?mod=viewthread&tid=34023) php 5.6 了，
请问这个 patch 能用在 Laravel 4.2 上吗？

**Comment by chariothy** [comment]
是吗？真是个好消息。4.2应该是没问题的，毕竟4.x的结构都一样。不过既然php5.6了，就可以考虑移植laravel 5了。

发送自 Outlook

On Mon, Apr 20, 2015 at 12:30 AM -0700, "viko16" notifications@github.com wrote:

SAE 已经开始测试 php 5.6 了，

请问这个 patch 能用在 Laravel 4.2 上吗？
